### PR TITLE
Add 'Copy' Icon to chat messages, Add tooltip to message icons

### PR DESCRIPTION
**Pull request by ZemyCode**
### Feature 1
Toggleable 'Copy' icon to copy a chat message. Icon appears next to reply/pin icons:
image

Clicking the icon copies the chat message and shows a toast for 1 second confirming the message was copied:
image

**This copies purely the chat message, so the clipboard in the above example results in: "Hello"**

This feature is toggleable and true by default, a new subcategory named "Message tools" in "Chat" settings is added as I was unsure which subcategory this would fit in:
image

It is understandable if this feature is not approved as some chats may not appreciate easier copy pastas... but there are some chats who would be a fan of it. Let me know if I should remove feature 1 and just keep feature 2 as I believe feature 2 is useful.

### Feature 2
Tooltips for the reply/pin/copy icons on mouse hover:
image
image
image

This feature utilizes the "BadgeTooltip" component, so possibly rename BadgeTooltip to a more general name if this feature stays?

### CODE REVIEW

**Comment by AnatoleAM** [comment]
Run `make format` to fix ci warnings

**Review by Melonify — APPROVED** [review]

**Review by AnatoleAM — APPROVED** [review]
Appreciate the contribution. Send your twitch username here if you'd like the contributor badge 🫡

**Comment by ZemyCode** [comment]
> Appreciate the contribution. Send your twitch username here if you'd like the contributor badge 🫡

Thanks! It was fun to work on, I plan on possibly making more contributions. My twitch name is "Zemy".

**Comment by AnatoleAM** [comment]
@ZemyCode entitled :+1: via the magic of #472 this is already live right now on the nightly build :point_right: :point_right:

**Pull request merged**
