### PR TITLE
feat: add an option to highlight messages from moderators

### PR DESCRIPTION
**Pull request by lumynou5**
This adds an option to highlight messages from moderators.
The green (`#00bb00`) for highlights is the same color on the moderator badge.

This is reopen of #486.

### CODE REVIEW

**Comment by lumynou5** [comment]
Please check it out.

**Comment by AnatoleAM** [comment]
Closing this because moving forward we should be inferring the values from Twitch's own highlight settings, this is too confusing to the end user to be met with 2 identical but clashing systems.

**Comment by lumynou5** [comment]
> Closing this because moving forward we should be inferring the values from Twitch's own highlight settings, this is too confusing to the end user to be met with 2 identical but clashing systems.

Where is Twitch's own settings?

**Comment by lumynou5** [comment]
Thanks.
It seems designed for streamers and moderators, but I want viewers can see highlights. I think we can read Twitch's settings for streamers and mods (sync between them?), and for viewers they can adjust their own.

**Pull request closed without merging**
