### PR TITLE
changed readme to include better windows instructions

### PR DESCRIPTION
**Pull request by ZKLaurin**
Added more clear steps for Windows and also added the License for a quicker overview.

### CODE REVIEW

**Review by Melonify — CHANGES_REQUESTED** [review]
This is wrong information, if anything it should just instruct people on how to install GNU Make on Windows, instead of trying to awkwardly sidestep our build chain.

**Comment by Melonify** [comment]
Also the license paragraph is not correct, and I think that entire section should be omitted.

**Comment by ZKLaurin** [comment]
I basically removed all the stuff for windows and just made a step by step guide on how to install the necessary packages for WSL.

**Comment by ZKLaurin** [comment]
I need to close this PR, because i commited into the master branch

**Pull request closed without merging**
