### PR TITLE
feat: Channel specific highlights via Channel name

### PR DESCRIPTION
**Pull request by MisterXYCB**
Allows to set a channel id for custom highlights

### CODE REVIEW

**Review by AnatoleAM — CHANGES_REQUESTED** [review]
Channel ID isn't a user-friendly parameter, it's virtually impossible for a regular user to find that value. This would need to either use login name, or make an intermediate query for the channel ID. (see `useApollo` & related code for interacting with Twitch's internal apollo instance)

**Comment by AnatoleAM** [comment]
In general I think this isn't the best approach to take, it would be best to implement a profile system with condition-based activation.

**Comment by MisterXYCB** [comment]
Changed it to work with channel names

**Comment by MisterXYCB** [comment]
@AnatoleAM changed it to use channel name

**Comment by AnatoleAM** [comment]
Closing as this is a wrong approach at implementing a feature like this. It should be part of a wider profile system

**Pull request closed without merging**
