### PR TITLE
fix(twitch): broken chat embeds

### PR DESCRIPTION
**Pull request by pimothyxd**
If a channel moderator received a "suspicious user" message, the message would not get highlighted. A message containing a clip also seemed to not get embedded. The issue causing this seemed to have been Twitch changing their pubsub client.

See the following examples:

image

which should now look like this:

image

and:

image

should now look like this:

image

Should fix: #973

### CODE REVIEW

**Comment by scotsdez** [comment]
@pimothyxd Just in case you hadn't seen the above about the CLA.

Thanks for fixing 973 - I've actually had to stop using 7TV in the meantime as it was making moderation quite difficult, so I'm quite keen to see this drop in a future release.

**Comment by tlstommy** [comment]
> @pimothyxd Just in case you hadn't seen the above about the CLA.
> 
> Thanks for fixing 973 - I've actually had to stop using 7TV in the meantime as it was making moderation quite difficult, so I'm quite keen to see this drop in a future release.

Is the current extension going to be supported while the new version is being built? or will we have to wait for the new version for extension PRs like this one to be reviewed?

**Comment by TroyKomodo** [comment]
Does this still work?
image

**Comment by pimothyxd** [comment]
> Does this still work? image

Should be all good now

**Pull request merged**
