### PR TITLE
fix: added iframe support 

### PR DESCRIPTION
**Pull request by tlstommy**
added "all_frames":true, to manifest to support iframes

### CODE REVIEW

**Review by Melonify — CHANGES_REQUESTED** [review]
We don't actually want to run on embeds, this would cause massive problems for sites that embed a lot of clips/embeds, like LSF.

It may be possible to check if the page is specifically a chat embed, and only inject then. But these are pretty rare, and I'm not sure that its worth the effort.

**Comment by Melonify** [comment]
Is there a specific use-case where running in embeds is desirable?

**Comment by tlstommy** [comment]
I have a chrome extension I'm using/developing that will inject other channels chats as an iframe onto a stream, and those embedded iframes won't show chat unless that's enabled.

Is there another way to do this? Or enable it so it will only allow for twitch.tv embeds?

I'd love the help if you are able!

**Comment by tlstommy** [comment]
I would only need it to embed the twitch chat pop out

**Comment by tlstommy** [comment]
Ive got it to work (i think) with the content script as this `(function () { "use strict"; 

//Check if it's an iframe and is a popout
if (window !== window.top) {
    let currentIframeSrc = window.location.href;
    if (!currentIframeSrc.startsWith("https://www.twitch.tv/popout")) {
        return;
    }
}



const r = "seventv-app-broadcast-channel"; async function d() { const e = document.createElement("div"); e.id = "seventv-emoji-container", e.style.display = "none", e.style.position = "fixed", e.style.top = "-1px", e.style.left = "-1px"; const t = chrome.runtime.getURL("assets/emoji"), i = 11; for (let s = 0; s < i; s++) { const c = (await fetch(t + "/emojis" + s + ".svg")).text(), n = document.createElement("div"); n.id = "emojis" + s, n.innerHTML = await c, e.appendChild(n) } document.head.appendChild(e) } const u = () => { const e = document.createElement("script"); e.src = chrome.runtime.getURL("site.js"), e.id = "seventv-extension", e.type = "module", e.setAttribute("worker_url", chrome.runtime.getURL("worker.js")), e.setAttribute("extension_origin", chrome.runtime.getURL("")); { const t = document.createElement("link"); t.rel = "stylesheet", t.type = "text/css", t.href = chrome.runtime.getURL("assets/seventv.style.3.0.15.css"), t.setAttribute("charset", "utf-8"), t.setAttribute("content", "text/html"), t.setAttribute("http-equiv", "content-type"), t.id = "seventv-stylesheet", (document.head || document.documentElement).appendChild(t) } (document.head || document.documentElement).appendChild(e), setTimeout(() => { d() }, 1e3) }, a = new BroadcastChannel(r); u(), a.addEventListener("message", e => { switch (e.data.type) { case "seventv-create-permission-listener": { const { selector: t, id: i, origins: s, permissions: c } = e.data.data, n = document.querySelector(t); if (!n) return; n.addEventListener("switch", () => { chrome.runtime.sendMessage({ type: "permission-request", data: { id: i, origins: s, permissions: c } }, {}, o => { o && a.postMessage({ type: "seventv-permission-granted", data: { id: o.id, granted: o.granted } }) }) }); break } case "seventv-update-check": chrome.runtime.sendMessage({ type: "update-check" }, t => { a.postMessage({ type: "seventv-update-check-result", data: { status: t.status, version: t.version } }) }) } }), chrome.runtime.onMessage.addListener(e => { switch (e.type) { case "update-ready": { m(e.data.version ?? ""); break } case "settings-sync": { p(e.data.settings ?? []); break } } }); function m(e) { a.postMessage({ type: "seventv-update-ready", data: { version: e } }) } function p(e) { a.postMessage({ type: "seventv-settings-sync", data: { nodes: e } }) } })();
 ` however im getting some trouble generating it.

**Comment by tlstommy** [comment]
Ok, I added in a check so that even though all_frames is true, it also will check if it is a Twitch popout iframe before injecting. It works locally for me, but please let me know if there is something I should change!

**Comment by tlstommy** [comment]
This would only look for twitch chat embed too, not any twitch embed

**Comment by jaaneh** [comment]
Working on a site personally, and no emotes are working. Something like this would be pretty great. Pretty sad to not have emote support on embeds.

@tlstommy My chat embed URL looks like this, and wouldn't currently be picked up by your checker. `https://www.twitch.tv/embed/<channel>/chat`

**Comment by tlstommy** [comment]
> Working on a site personally, and no emotes are working. Something like this would be pretty great. Pretty sad to not have emote support on embeds.
> 
> @tlstommy My chat embed URL looks like this, and wouldn't currently be picked up by your checker. `https://www.twitch.tv/embed/<channel>/chat`
> 
> Related #187 #193

It should detect it now!

**Comment by tlstommy** [comment]
updated to new version, i think i formatted the nightly changelog correctly.

**Review by tlstommy — COMMENTED** [review]
I have added logic to check specifically for chat embeds.

**Comment by tlstommy** [comment]
https://github.com/SevenTV/Extension/pull/964

**Pull request closed without merging**
