### PR TITLE
Added new chat autocompletion setting option. Double click on the mes…

### PR DESCRIPTION
**Pull request by Batyodie**
Added new chat autocompletion setting option. Double click on the message author(#387)
 
 As it was before adding the feature:

[screencast-www.twitch.tv-2023.04.16-18_00_23.webm](https://user-images.githubusercontent.com/61266300/232321755-f2713de3-6713-49b5-a33e-6e47cb367710.webm)

When double-clicking on the nickname of the author of the message in the input text of the message, the nickname did not appear, which can be referred to in a future message.

What's added with the new feature:

- New setting in chat autocompletion options "Double click on the message author". Disabled by default.

image

- If the setting is enabled, now when you double-click on the nickname of the author of the message, his nickname will be added to the message input field:

[screencast-www.twitch.tv-2023.04.16-18_12_31.webm](https://user-images.githubusercontent.com/61266300/232322422-3d9108c8-faf5-4290-806a-939b1c2e406e.webm)

I also checked the feature after transitions between different twitch streamers.

### CODE REVIEW

**Comment by Batyodie** [comment]
@ayyybubu I can do it, but it's not clear how it should be displayed in the settings menu. 
I need to make a dropdown list, where the default value will be, is the author's nickname quick selection disabled?

**Comment by ayyybubu** [comment]
Yeah the dropdown list is the way to go. It's kinda whatever if the setting is on or off by default since its not really disruptive

**Comment by Batyodie** [comment]
@ayyybubu Made edits. Updated function descriptions in settings, corrected code, corrected logs for nightly release.

[screencast-github.com-2023.04.18-21_44_53.webm](https://user-images.githubusercontent.com/61266300/232874370-801e0fbc-d69c-4591-aa92-70c38df13bf6.webm)


Tested:

- Toggle click option.

- Saving the selected setting after reboot

- the settings work in the test chat and when switching to other real streams.

**Comment by Batyodie** [comment]
@ayyybubu Corrected.

**Comment by Batyodie** [comment]
@ayyybubu  How long does it usually take to accept a request?
As I understand it, AnatoleAM is in charge here. Do all pull requests go through it?

And you can also see other requests, too, please.
#509
#499

**Comment by Batyodie** [comment]
@berghall Hi. Please, can you review this pr?

**Comment by barbaduk** [comment]
bump. 
Many versions have passed, will this be reviewed and added?..

**Comment by TroyKomodo** [comment]
Features against this repo wont be implemented, we are going to rewrite the extension on this [repo](https://github.com/SevenTV/SevenTV).

**Pull request closed without merging**
